imports:
  - orchestration.yaml

parameters:
  odapcapstone:
    datalake:
      base_path: '/%kernel.environment%'

  datalakebundle:
    table:
      name_template: '%kernel.environment%_{identifier}'
      defaults:
        base_path: '%odapcapstone.datalake.base_path%'
        target_path: !expr 'base_path + "/" + db_identifier + "/" + table_identifier + ".delta"'
