imports:
  - orchestration.yaml

parameters:
  # Project custom configuration
  odapcapstone:
    datalake:
      base_path: 'dbfs:/%kernel.environment%/odap-capstone'
  
  # Feature store configuration
  featurestorebundle:
    # Paths
    base_path: '%odapcapstone.datalake.base_path/{entity}'
    db_name: '%kernel.environment%_odap_academy_feature_store'
    # Features
    entities:
      daniela_vlasceanu:
        id_column: "customer_id"
        id_column_type: "integer"
    # Defaults
    widgets:
      defaults:
        timestamp: "2022-06-06"
        target_date_from: "2021-06-06"
        target_date_to: "2022-06-06"
        target_time_shift: "0d"
    time_windows: ["3d", "5d"]
    metadata:
      table:
        table_template: 'features_metadata_{entity}'
  
  # Datalake tables configuration
  datalakebundle:
    table:
      name_template: '%kernel.environment%_{identifier}'
      defaults:
        base_path: '%odapcapstone.datalake.base_path%'
        target_path: !expr 'base_path + "/" + db_identifier + "/" + table_identifier + ".delta"'
